service: layers

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  stage: ${opt:stage, 'dev'}

layers:
  expressPgMoment:
    path: express-pg-moment
    description: Layer with ExpressJS, MomentJS, Serverless HTTP, PostgreSQL client
    compatibleRuntimes:
      - nodejs12.x

resources:
  Outputs:
    ExpressPgMomentLayerExport:
      Value:
        Ref: ExpressPgMomentLambdaLayer
      Export:
        Name: ExpressPgMomentLambdaLayer
