service: test-layer

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-3
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: index.handler
    layers:
      - ${cf:layers-${self:provider.stage}.ExpressPgMomentLayerExport}
      - ${cf:layers-${self:provider.stage}.LoggingLayerExport}
      # - {Ref: ExpressPgMomentLambdaLayer}
      # - arn:aws:lambda:eu-west-3:660349859862:layer:expressPgMoment:3
    events:
      - http:
          path: /time
          method: GET
          cors: true
package:
  exclude:
    - node_modules/logging
plugins:
  - serverless-plugin-typescript
  - serverless-offline
